/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author kunal
 */
public class doctorFrame extends javax.swing.JFrame {

    /**
     * Creates new form doctorFrame
     */
    public doctorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientTopPanel = new javax.swing.JPanel();
        patientTopLbl1 = new javax.swing.JLabel();
        patientTopLbl = new javax.swing.JLabel();
        pateintHeadingLbl = new javax.swing.JLabel();
        patientIdLbl = new javax.swing.JLabel();
        patientNameLbl = new javax.swing.JLabel();
        patientAddressLbl = new javax.swing.JLabel();
        patientIdTxt = new javax.swing.JTextField();
        patientIdTxt1 = new javax.swing.JTextField();
        patientBloodGpDropdown = new javax.swing.JComboBox<>();
        patientPhoneLbl = new javax.swing.JLabel();
        patientPhoneLbl1 = new javax.swing.JLabel();
        patientPhoneLbl2 = new javax.swing.JLabel();
        patientIdTxt2 = new javax.swing.JTextField();
        patientIdTxt3 = new javax.swing.JTextField();
        patientIdTxt4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientTopPanel.setBackground(new java.awt.Color(0, 51, 51));

        patientTopLbl1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        patientTopLbl1.setForeground(new java.awt.Color(255, 255, 255));
        patientTopLbl1.setText("Manage Patients");

        patientTopLbl.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        patientTopLbl.setForeground(new java.awt.Color(255, 255, 255));
        patientTopLbl.setText("Hospital Management System");

        javax.swing.GroupLayout patientTopPanelLayout = new javax.swing.GroupLayout(patientTopPanel);
        patientTopPanel.setLayout(patientTopPanelLayout);
        patientTopPanelLayout.setHorizontalGroup(
            patientTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientTopPanelLayout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(patientTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientTopPanelLayout.createSequentialGroup()
                        .addComponent(patientTopLbl)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientTopPanelLayout.createSequentialGroup()
                        .addComponent(patientTopLbl1)
                        .addGap(258, 258, 258))))
        );
        patientTopPanelLayout.setVerticalGroup(
            patientTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientTopPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(patientTopLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientTopLbl1)
                .addGap(12, 12, 12))
        );

        pateintHeadingLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        pateintHeadingLbl.setText("Patient Information");

        patientIdLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientIdLbl.setText("ID :");

        patientNameLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientNameLbl.setText("PATID :");

        patientAddressLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientAddressLbl.setText("Name :");

        patientIdTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientIdTxt1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientBloodGpDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        patientPhoneLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientPhoneLbl.setText("Symptoms :");

        patientPhoneLbl1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientPhoneLbl1.setText("Diagnosis :");

        patientPhoneLbl2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientPhoneLbl2.setText("Medicines :");

        patientIdTxt2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientIdTxt3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientIdTxt4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientAddressLbl)
                    .addComponent(patientNameLbl)
                    .addComponent(patientIdLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(patientBloodGpDropdown, 0, 160, Short.MAX_VALUE)
                    .addComponent(patientIdTxt1)
                    .addComponent(patientIdTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientPhoneLbl)
                    .addComponent(patientPhoneLbl2)
                    .addComponent(patientPhoneLbl1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientIdTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientIdTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientIdTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pateintHeadingLbl)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(patientTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pateintHeadingLbl)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIdLbl)
                    .addComponent(patientIdTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientPhoneLbl)
                    .addComponent(patientIdTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLbl)
                    .addComponent(patientBloodGpDropdown)
                    .addComponent(patientPhoneLbl1)
                    .addComponent(patientIdTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientAddressLbl)
                    .addComponent(patientIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientPhoneLbl2)
                    .addComponent(patientIdTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pateintHeadingLbl;
    private javax.swing.JLabel patientAddressLbl;
    private javax.swing.JComboBox<String> patientBloodGpDropdown;
    private javax.swing.JLabel patientIdLbl;
    private javax.swing.JTextField patientIdTxt;
    private javax.swing.JTextField patientIdTxt1;
    private javax.swing.JTextField patientIdTxt2;
    private javax.swing.JTextField patientIdTxt3;
    private javax.swing.JTextField patientIdTxt4;
    private javax.swing.JLabel patientNameLbl;
    private javax.swing.JLabel patientPhoneLbl;
    private javax.swing.JLabel patientPhoneLbl1;
    private javax.swing.JLabel patientPhoneLbl2;
    private javax.swing.JLabel patientTopLbl;
    private javax.swing.JLabel patientTopLbl1;
    private javax.swing.JPanel patientTopPanel;
    // End of variables declaration//GEN-END:variables
}
