/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author kunal
 */
public class patientFrame extends javax.swing.JFrame {

    /**
     * Creates new form patientFrame
     */
    public patientFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientTopPanel = new javax.swing.JPanel();
        patientTopLbl1 = new javax.swing.JLabel();
        patientTopLbl = new javax.swing.JLabel();
        patientPanel = new javax.swing.JPanel();
        patientIdLbl = new javax.swing.JLabel();
        patientIdTxt = new javax.swing.JTextField();
        patientNameTxt = new javax.swing.JTextField();
        patientPhoneTxt = new javax.swing.JTextField();
        patientAgeTxt = new javax.swing.JTextField();
        patientNameLbl = new javax.swing.JLabel();
        pateintHeadingLbl = new javax.swing.JLabel();
        patientPhoneLbl = new javax.swing.JLabel();
        patientAgeLbl = new javax.swing.JLabel();
        addPatientBtn = new javax.swing.JButton();
        updateDoctorBtn = new javax.swing.JButton();
        deleteDoctorBtn = new javax.swing.JButton();
        clearDoctorBtn = new javax.swing.JButton();
        doctorTableHeaderPanel = new javax.swing.JPanel();
        patientTableLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTbl = new javax.swing.JTable();
        patientScreenHomeBtn = new javax.swing.JButton();
        patientAddressLbl = new javax.swing.JLabel();
        patientAddressTxt = new javax.swing.JTextField();
        patientGenderLbl = new javax.swing.JLabel();
        patientVitalLbl = new javax.swing.JLabel();
        patientVitalTxt = new javax.swing.JTextField();
        patientPathoLbl = new javax.swing.JLabel();
        patientPathoTxt = new javax.swing.JTextField();
        patientGenderDropdown = new javax.swing.JComboBox<>();
        patientBloodGpLbl = new javax.swing.JLabel();
        patientBloodGpDropdown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientTopPanel.setBackground(new java.awt.Color(0, 51, 51));

        patientTopLbl1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        patientTopLbl1.setForeground(new java.awt.Color(255, 255, 255));
        patientTopLbl1.setText("Manage Patients");

        patientTopLbl.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        patientTopLbl.setForeground(new java.awt.Color(255, 255, 255));
        patientTopLbl.setText("Hospital Management System");

        javax.swing.GroupLayout patientTopPanelLayout = new javax.swing.GroupLayout(patientTopPanel);
        patientTopPanel.setLayout(patientTopPanelLayout);
        patientTopPanelLayout.setHorizontalGroup(
            patientTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientTopPanelLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(patientTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientTopPanelLayout.createSequentialGroup()
                        .addComponent(patientTopLbl)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientTopPanelLayout.createSequentialGroup()
                        .addComponent(patientTopLbl1)
                        .addGap(258, 258, 258))))
        );
        patientTopPanelLayout.setVerticalGroup(
            patientTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientTopPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(patientTopLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientTopLbl1)
                .addGap(12, 12, 12))
        );

        patientIdLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientIdLbl.setText("ID :");

        patientIdTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientNameTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientPhoneTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientAgeTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientNameLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientNameLbl.setText("PATID :");

        pateintHeadingLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        pateintHeadingLbl.setText("Patient Information");

        patientPhoneLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientPhoneLbl.setText("Phone :");

        patientAgeLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientAgeLbl.setText("Age :");

        addPatientBtn.setBackground(new java.awt.Color(0, 0, 0));
        addPatientBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        addPatientBtn.setForeground(new java.awt.Color(255, 255, 255));
        addPatientBtn.setText("ADD");

        updateDoctorBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateDoctorBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        updateDoctorBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateDoctorBtn.setText("UPDATE");

        deleteDoctorBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteDoctorBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        deleteDoctorBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteDoctorBtn.setText("DELETE");

        clearDoctorBtn.setBackground(new java.awt.Color(0, 0, 0));
        clearDoctorBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        clearDoctorBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearDoctorBtn.setText("CLEAR");

        doctorTableHeaderPanel.setBackground(new java.awt.Color(0, 51, 51));

        patientTableLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        patientTableLbl.setForeground(new java.awt.Color(255, 255, 255));
        patientTableLbl.setText("Encounter History");

        javax.swing.GroupLayout doctorTableHeaderPanelLayout = new javax.swing.GroupLayout(doctorTableHeaderPanel);
        doctorTableHeaderPanel.setLayout(doctorTableHeaderPanelLayout);
        doctorTableHeaderPanelLayout.setHorizontalGroup(
            doctorTableHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorTableHeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientTableLbl)
                .addGap(285, 285, 285))
        );
        doctorTableHeaderPanelLayout.setVerticalGroup(
            doctorTableHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, doctorTableHeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientTableLbl)
                .addContainerGap())
        );

        patientTbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Vital Signs", "Phone", "Age", "Gender", "Pathologies", "Blood Group"
            }
        ));
        patientTbl.setRowHeight(32);
        patientTbl.setSelectionBackground(new java.awt.Color(0, 0, 0));
        patientTbl.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(patientTbl);

        patientScreenHomeBtn.setBackground(new java.awt.Color(0, 0, 0));
        patientScreenHomeBtn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        patientScreenHomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        patientScreenHomeBtn.setText("HOME");
        patientScreenHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientScreenHomeBtnActionPerformed(evt);
            }
        });

        patientAddressLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientAddressLbl.setText("Name :");

        patientAddressTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientGenderLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientGenderLbl.setText("Gender :");

        patientVitalLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientVitalLbl.setText("Vital Signs :");

        patientVitalTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientPathoLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientPathoLbl.setText("Pathologies :");

        patientPathoTxt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        patientGenderDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        patientGenderDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientGenderDropdownActionPerformed(evt);
            }
        });

        patientBloodGpLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        patientBloodGpLbl.setText("Blood Group :");

        patientBloodGpDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout patientPanelLayout = new javax.swing.GroupLayout(patientPanel);
        patientPanel.setLayout(patientPanelLayout);
        patientPanelLayout.setHorizontalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doctorTableHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(addPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(updateDoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(deleteDoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(clearDoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(patientScreenHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientBloodGpLbl)
                    .addComponent(patientVitalLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientAddressLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientNameLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientIdLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientNameTxt)
                    .addComponent(patientIdTxt)
                    .addComponent(patientAddressTxt)
                    .addComponent(patientVitalTxt)
                    .addComponent(patientBloodGpDropdown, 0, 177, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientAgeLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientGenderLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientPathoLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientPhoneLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientPhoneTxt)
                    .addComponent(patientAgeTxt)
                    .addComponent(patientPathoTxt)
                    .addComponent(patientGenderDropdown, 0, 177, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pateintHeadingLbl)
                .addGap(269, 269, 269))
        );
        patientPanelLayout.setVerticalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pateintHeadingLbl)
                .addGap(12, 12, 12)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIdLbl)
                    .addComponent(patientIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientPhoneLbl))
                .addGap(18, 18, 18)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientAgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(patientAgeLbl))
                    .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(patientNameLbl)))
                .addGap(18, 18, 18)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientAddressLbl)
                    .addComponent(patientGenderDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientGenderLbl))
                .addGap(18, 18, 18)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPathoLbl)
                    .addComponent(patientPathoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientVitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientVitalLbl))
                .addGap(18, 18, 18)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientBloodGpLbl)
                    .addComponent(patientBloodGpDropdown))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateDoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearDoctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(doctorTableHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientScreenHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(patientTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(patientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(patientTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 496, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(95, Short.MAX_VALUE)
                    .addComponent(patientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientScreenHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientScreenHomeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientScreenHomeBtnActionPerformed

    private void patientGenderDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientGenderDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientGenderDropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientBtn;
    private javax.swing.JButton clearDoctorBtn;
    private javax.swing.JButton deleteDoctorBtn;
    private javax.swing.JPanel doctorTableHeaderPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pateintHeadingLbl;
    private javax.swing.JLabel patientAddressLbl;
    private javax.swing.JTextField patientAddressTxt;
    private javax.swing.JLabel patientAgeLbl;
    private javax.swing.JTextField patientAgeTxt;
    private javax.swing.JComboBox<String> patientBloodGpDropdown;
    private javax.swing.JLabel patientBloodGpLbl;
    private javax.swing.JComboBox<String> patientGenderDropdown;
    private javax.swing.JLabel patientGenderLbl;
    private javax.swing.JLabel patientIdLbl;
    private javax.swing.JTextField patientIdTxt;
    private javax.swing.JLabel patientNameLbl;
    private javax.swing.JTextField patientNameTxt;
    private javax.swing.JPanel patientPanel;
    private javax.swing.JLabel patientPathoLbl;
    private javax.swing.JTextField patientPathoTxt;
    private javax.swing.JLabel patientPhoneLbl;
    private javax.swing.JTextField patientPhoneTxt;
    private javax.swing.JButton patientScreenHomeBtn;
    private javax.swing.JLabel patientTableLbl;
    private javax.swing.JTable patientTbl;
    private javax.swing.JLabel patientTopLbl;
    private javax.swing.JLabel patientTopLbl1;
    private javax.swing.JPanel patientTopPanel;
    private javax.swing.JLabel patientVitalLbl;
    private javax.swing.JTextField patientVitalTxt;
    private javax.swing.JButton updateDoctorBtn;
    // End of variables declaration//GEN-END:variables
}
